version: '3.8'
services:
    nodeapp:
        image: nodeapp
        build:
            context: "./NodeApp/"
        ports:
            - "8080:8080"

    statsd:
        image: graphiteapp/graphite-statsd:latest
        ports:
          - "8125:8125" 
        links:
            - "nodeapp"